### ISSUE TITLE
Exception in server tick loop when using #minecraft:load or #minecraft:tick function tags

### ISSUE THREAD

**Issue by misode** [hugeBlack/McfDebugger_Extension#1]
When starting the debugger my game crashes. The data pack contains the `minecraft:load` tag which calls a simple function. Running the function or function tag from chat works fine. This also happens with the `minecraft:tick` tag.

See the following data pack setup:
![image](https://user-images.githubusercontent.com/17352009/108744120-dad65f80-7539-11eb-97af-d8a2b10c34aa.png)

Game version: 1.16.5
Extension version: 0.0.2
Mod version: 1.0.2
Crash report: [crash-2021-02-22_18.13.46-server.txt](https://github.com/hugeBlack/McfDebugger_Extension/files/6023815/crash-2021-02-22_18.13.46-server.txt)

**Comment by misode** [comment]
I just realized I should've made this in the Mod repository, but I guess you can transfer it

**Comment by hugeBlack** [comment]
Thanks for reporting! I will fix this as soon as possible. Apologize for not doing enough tests.
Also, it’s ok to report any issue in both repositories.

**Comment by hugeBlack** [comment]
Sorry for being late.
I think I fixed it and you can download it [here](https://github.com/hugeBlack/McfDebugger_Mod/releases).
If you meet any other problems, please continue to contact me.

**Comment by misode** [comment]
I can confirm the fix works. Thanks!
