### ISSUE TITLE
Can not connect to the debug Websocket server

### ISSUE THREAD

**Issue by MrKleeblatt** [hugeBlack/McfDebugger_Extension#3]
Hey, I just downloaded your extension, but got an error althought I did everything you wrote in the description... Is this a bug or is it on me?
VSCode 1.56.2
Electron 12.0.4
Windows 10 Pro x64
Debugger version v0.1.1

**Comment by hugeBlack** [comment]
It’s weird that this happened.
It seemed that you didn’t report the version of the mod part, so did you install it, or did it work?
If you’ve changed the port in the mod version, make sure to put the same port in launch.json.
If this keeps happening, let me know.

**Comment by MrKleeblatt** [comment]
Oh wait, I just forgot to put the mod in the right folder... Sorry for that.
